### ISSUE TITLE
Video pauses on bringing app to the foreground with AirPlay

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#128]
Hi,

We have the Kaltura player set up to use Apple’s AirPlay. We’ve noticed that when playing a video over AirPlay and sending the app to the background, while the video continues to play on AppleTV (which is desired behavior), resuming our app causes the video to pause. Ideally, the video would continue playing after resuming our app.

We have noticed that when the app comes back to the foreground, the Kaltura player is receiving a 'pause' event from its web component (html5&javascript) so that is stopping the video.

Would it be possible to change this behavior or make it configureable in some way?

Thank you.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

You can configure it by using of background/foreground methods.
When you enter foreground send:

    [self.player.playerController play];

Best,

Eliza

**Comment by jabberdabber** [comment]
Hi Eliza,

We've found that this change doesn't have an effect. But a change one of our devs made to KPlayer's removePlayer method seemed to solve the problem.

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

We already have:

     self.layer = nil;

in dealloc after player is removed.

First of all it make sure that when you remove player then you have to do:

    self.player = nil; // this will call dealloc

Another point, please read the following doc to make sure you use our methods in proper way:
https://github.com/kaltura/player-sdk-native-ios/wiki/Player-Lifecycle---API

Best,

Eliza

**Comment by jabberdabber** [comment]
Hi Eliza,

We're finding that KPlayer's dealloc method is not called and therefore the layer is not released.

We have this code for managing the KPViewController object:

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    self.player.view.frame = (CGRect){0, 64, 320, 180};
    [self.player loadPlayerIntoViewController:self];
    [self.view addSubview:_player.view];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    [self.player dismissViewControllerAnimated:NO completion:nil];
    [self.player removePlayer];
    self.player = nil;
}

When running the app with a break point placed in KPlayer's dealloc method, we find that it is never hit when the viewWillDisappear method is invoked.

**Comment by ElizaSapir** [comment]
Hey @jabberdabber ,

Please try the following:

1. remove 
   
    [self.player dismissViewControllerAnimated:NO completion:nil];

2. Use 

    viewDidDisappear

Let me know if it helped!

Best,

Eliza

**Comment by jabberdabber** [comment]
Hi Eliza,

Unfortunately, your suggestion does not work. However, we think we understand what the problem is.

This line in the KPlayer class at line 50 creates, we believe, a circular reference between the player object and the _layer object:

_layer = [AVPlayerLayer playerLayerWithPlayer:self];

As a result, when the player is later nilled out by the player factory (at line 171 in KPlayerFactory.m) its dealloc method is not called as the _layer object still contains a reference to it.

Either nilling out the _layer object in KPlayer's removePlayer method or setting the _layer's player object to nil breaks the circular reference. As a result, when the player factor nils out the player object, it is truly released and its dealloc method is invoked.

**Comment by jabberdabber** [comment]
Hi Eliza,

Unfortunately, your suggestion does not work. However, we think we understand what the problem is.
This line in the KPlayer class at line 50 creates, we believe, a circular reference between the player object and the _layer object:

_layer = [AVPlayerLayer playerLayerWithPlayer:self];

As a result, when the player is later nilled out by the player factory (at line 171 in KPlayerFactory.m) its dealloc method is not called as the _layer object still contains a reference to it.

Either nilling out the _layer object in KPlayer's removePlayer method or setting the _layer's player property to nil breaks the circular reference. As a result, when the player factor nils out the player object, it is truly released and its dealloc method is invoked.

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

We found the issue this weak i am going to tag a new version v2.3 it will include the needed fix.

Thank you very much for cooperation. 

Best,
Eliza
