### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#135]
Hi,

I'm trying to load a playlist with the same, example code in the getting started: (I changed the config with my own values):

- (KPViewController *)player {
    if (!_player) {
        // Account Params
        KPPlayerConfig *config = [[KPPlayerConfig alloc] initWithServer:@"http://vodgc.com"
                                                               uiConfID:@"23448994"
                                                              partnerId:@"109"];
        // Video Entry
        [config setEntryId:@"0_79j3ff7e"]; // Here I set a playlist id
        
        // Setting this property will cache the html pages in the limit size
        config.cacheSize = 0.8;
        _player = [[KPViewController alloc] initWithConfiguration:config];
    }
    return _player;
}

But didn't work, when I try to do it I receive this output: (if a replace for a video entry id works perfect)

> 2016-03-17 11:59:20.397 multichanelMockUp[13741:5462917] NSRect: {{0, 0}, {414, 736}}
> 2016-03-17 11:59:20.516 multichanelMockUp[13741:5462917] HTTP:: http://vodgc.com/p/109/sp/10900/embedIframeJs/uiconf_id/23448994/entry_id/0_79j3ff7e?wid=_109&uiconf_id=23448994&entry_id=0_79j3ff7e&iframeembed=true#localContentId=
> 2016-03-17 11:59:20.584 multichanelMockUp[13741:5463012] 
> ::Error:: -[NSString(Cache) setDateAttributeAtPath:] (line:169)
> The file “data” doesn’t exist.
> 2016-03-17 11:59:20.749 multichanelMockUp[13741:5463013] 
> ::Error:: -[NSString(Cache) deleteFile] (line:191)
> Error Domain=NSCocoaErrorDomain Code=4 "“be657259719f2b499b8f0181d4c096ba” couldn’t be removed." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/61616363-9551-4E3F-BBC5-35CFD833FE82/Documents/be657259719f2b499b8f0181d4c096ba, NSUserStringVariant=(
>     Remove
> ), NSUnderlyingError=0x1366a6300 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
> 2016-03-17 11:59:20.771 multichanelMockUp[13741:5463013] 
> ::Error:: -[NSString(Cache) setDateAttributeAtPath:] (line:169)
> The file “data” doesn’t exist.
> 2016-03-17 11:59:20.973 multichanelMockUp[13741:5463013] 
> ::Error:: -[NSString(Cache) setDateAttributeAtPath:] (line:169)
> The file “data” doesn’t exist.
> 2016-03-17 11:59:21.017 multichanelMockUp[13741:5463013] 
> ::Error:: -[NSString(Cache) setDateAttributeAtPath:] (line:169)
> The file “data” doesn’t exist.
> 2016-03-17 11:59:23.359 multichanelMockUp[13741:5463012] 
> ::Error:: -[NSString(Cache) setDateAttributeAtPath:] (line:169)
> The file “data” doesn’t exist.
> 2016-03-17 11:59:23.497 multichanelMockUp[13741:5463013] 
> ::Error:: -[NSString(Cache) deleteFile] (line:191)
> Error Domain=NSCocoaErrorDomain Code=4 "“b2bf336090ee19860cd89b5be97ccd4a” couldn’t be removed." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/61616363-9551-4E3F-BBC5-35CFD833FE82/Documents/b2bf336090ee19860cd89b5be97ccd4a, NSUserStringVariant=(
>     Remove
> ), NSUnderlyingError=0x1365e42e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

And this is an iPhone screenshot:

![iphone screenshot](https://cloud.githubusercontent.com/assets/4612832/13850908/c4110e68-ec3a-11e5-9078-68c20d5b8671.jpg)

Perhaps this is not the way to do this, but I couldn't found any example out there. 

Any ideas, examples? Thanks in advance!

Greetings,
Jonathan

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
playlist is not supported for now.
You can create a table view on your side and use changeMedia to switch between the entries.

**Comment by jonigl** [comment]
Thanks @ElizaSapir !

I would like to detect when a video entry finish and then use changeMedia to switch between the entries. But I could't make it work yet. One of my attempts is this one:

`- (void)kPlayer:(KPViewController *)player playerPlaybackStateDidChange:(KPMediaPlaybackState)state{
    NSLog(@"player state %ld", (long)state);
    if (state == KPMediaPlaybackStateEnded){
        NSLog(@"entry played");
    }
}`
*here is the complete code: [link](http://pastebin.com/TCHWBs79)
 perhaps it's a wrong way to do this.

Do you have any example? It would be very valuable to me.

**Comment by ElizaSapir** [comment]
Hey @jonigl,

Yes this is the way, BUT you forgot to attach our delegate:  KPViewControllerDelegate
This is the reason why your method never called.

**Comment by jonigl** [comment]
Thanks @ElizaSapir! You are helping me a lot! 

I tried to attach these delegate but it didn't work for me, probably i missed something important... I want to share my entire project with you: https://github.com/jonigl/kaltura-playlist-ios (In this project I will try to get a playlist work)

For short view this is what I add to my code: 

`@interface ViewController () <KPViewControllerDelegate>`

*here you have the complete code: [link](https://github.com/jonigl/kaltura-playlist-ios/blob/master/kaltura-playlist-ios/ViewController.m)

If you can advice me about how to getting work it would be appreciated a lot! Thanks in advance!!!

Greetings,
Jonathan

**Comment by ElizaSapir** [comment]
hi @jonigl,

Please attach: 

    self.player.delegate = self;

you can do it under viewDidAppear

**Comment by jonigl** [comment]
Hi @ElizaSapir, you are right!!! It works like a charm! You rules! Thanks very much :smiley:!
