### ISSUE TITLE
Error in adding Player

### ISSUE THREAD

**Issue by santhoshraj123** [kaltura/player-sdk-native-ios#141]
Just integrated Kaltura Native Player with new created app and integrated as it shows and if run the app it shows black screen with No Player created.

:Error:: -[KPlayerFactory addPlayerToController:] (line:40)
NO PLAYER CREATED

**Comment by ElizaSapir** [comment]
Hey @santhoshraj123,

Download the following example:
https://github.com/kaltura/player-sdk-demo-ios/tree/master/ovp/KChromecastDemo

It should help you to see how to implement and attach player SDK.

Best,
Eliza

**Comment by kaltura-hooks** [comment]
Hi @santhoshraj123,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by santhoshraj123** [comment]
Hi Eliza,

After i download and run the app i got the follwing error.

diff: /../Podfile.lock: No such file or directory

diff: /Manifest.lock: No such file or directory

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install'
or update your CocoaPods installation.

Could you please let me know how to do

**Comment by santhoshraj123** [comment]
[
  {"title": "Config URl",
  "cellType": 0}, - What needs to give here
  {"title": "Domain",
  "cellType": "https://cdnapi.kaltura.com"},
  {"title": "UIConf", - Where can we get config id 
  "cellType": 0},
  {"title": "PartnerId", - After login in settings we will get patner id
  "cellType": 0},
  {"title": "EntryId", - Entry id of videos asset
  "cellType": 0},
  {"title": "FlavourId", Where can we get FlavourId
  "cellType": 0},
  {"title": "KS", Where can we get KS
  "cellType": 0},
  {"title": "Offline URL", -We need to give local path of the url
  "cellType": 0},
  {"title": "Download", -what needs to be done here
  "cellType": 1},
  {"title": "History",what needs to be done here
  "cellType": 1},
  {"title": "Load Player",what needs to be done here
  "cellType": 1},
  {"title": "Fetch Configuration",what needs to be done here
  "cellType": 1}
  ]

Kindly please guide me how to run a video using kaltura native player for online and offline.I am struggling for one weeks.

**Comment by ElizaSapir** [comment]
Hey @santhoshraj123 ,

Let's focus on online, after downloading the demo you have to run:
  
    pod install

If you are not familiar with pods please read:
https://guides.cocoapods.org/using/getting-started.html

Let me know if it works for you.

Best,
Eliza

**Comment by santhoshraj123** [comment]
static-161:KChromecastDemo santhosh$ install cocoapods
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory

After this i don't know what to do.Pls guide me

**Comment by santhoshraj123** [comment]
now working fine .Could you please tell how to play offline videos

**Comment by ElizaSapir** [comment]
Hey @santhoshraj123,

Please use the following doc:
https://github.com/kaltura/player-sdk-native-ios/wiki/Offline-Playack

Let me know if you have questions. 

Best,
Eliza

**Comment by santhoshraj123** [comment]
Hey where can i get uiConfID.
i got partner and entry id but not able to find uiconfig ID.Pls suggest the way to get config id

**Comment by santhoshraj123** [comment]
Can we add player custom controls and we get the default one

**Comment by ElizaSapir** [comment]
Hey @santhoshraj123,

About uiconf id you can get it via KMC (the place where you configure the player).
About custom controls depends what you wish to do, you have 3 options:
1. You can customize the default skin via KMC studio.
2. You can create custom plugin (HTML,CCS,JS) with you own look and feel and use it with our SDK.
http://knowledge.kaltura.com/faq/how-create-kdp-plugins
3. You can create native iOS components.

**Comment by santhoshraj123** [comment]
Hey @ElizaSapir  its possible to add social sharing icons in the control list .so that user can share their videos to their social networking site.
