### ISSUE TITLE
"Cannot Open" error on attempting to playback downloaded video

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#168]
First, we download the entitlement, using a URL built following the guide early in this email thread. We don't specify a flavorID. The file downloads successfully, and actually opening this file in VLC on a desktop computer plays the first 10 seconds, then stops working. So this shows the file has downloaded, but is protected by WideVine DRM. So far, so good.

Immediately after the file is downloaded, we call the `getContextData` API, as this gives us an XML result with a list of `flavorAssets` `items` attached, each with a `flavorParamsId`. The entire XML result we get has been sent to Kaltura in an email.

We're using the first `flavorParamsId` result from here as our flavorID.

Then we build a `KPPlayerConfig` object, using the server as `https://cdnapisec.kaltura.com`, and with our `uiConfId` and `siteId`. We call `addConfigKey` to add our `ks` and we add our `entryId`. This is done exactly as it is if we were to stream a video:

```
let playerConfig = KPPlayerConfig(server: "https://cdnapisec.kaltura.com", uiConfID: credentials.uiConfID, partnerId: credentials.siteID)
playerConfig.addConfigKey("ks", withValue: kalturaSessionID)
playerConfig.entryId = entitlement.vendorEntryId
```

Then we call `KPLocalAssetsManager.registerAsset` using our `playerConfig`, `flavorID` and downloaded `fileURL` absolute path, which looks like this:

`file:///var/mobile/Containers/Data/Application/C017CF23-AA4A-4A79-BEB9-D8FEEA1E34AC/Documents/F7872297-8EB7-4D12-8A65-6F025A58B3E8`

This completes and calls the callback block without an error.

From there, we go to playback the video. We setup the KPViewController using the same configuration, as such:

```
self.player = KPViewController(configuration: config)
self.player.customSourceURLProvider = DownloadManager.sharedManager
self.player!.loadPlayerIntoViewController(self)

self.view.setNeedsLayout()

self.view.addSubview(self.player!.view)
```

`DownloadManager.sharedManager` implements `KPSourceURLProvider`, and returns the same fileURL as is shown above. I've logged this and confirmed that it's doing this correctly.

The player is laid out on the page, the Kaltura loading indicator appears over it, and then we get a visual error on screen, and the following error in the console:

> ::Error:: -[KPlayer prepareToPlayAsset:withKeys:] \(line:277)

> Cannot Open

I've attached the visual error as a screenshot.

I also tried playback without setting the `customSourceURLProvider`, just to ensure the video playback as a streaming video worked as usual, and this did work properly.
![img_4207](https://cloud.githubusercontent.com/assets/1865635/15190654/024c8aa6-17a9-11e6-9878-fa82be0593f7.PNG)

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by itaykinnrot** [comment]
We'll check it - just quick thing you can try- please make sure the downloaded file saved with .wvm

**Comment by ProjectDent** [comment]
I added the extension, but then upon calling `KPLocalAssetsManager.registerAsset` it just crashes with this crashlog:

>::Error:: -[KPPlayerConfig(Asset) resolvePlayerRootURL] (line:337)
>Error parsing uiConf json: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
>2016-05-12 11:24:56.910 Screeners[8277:1092580] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter'

**Comment by noamtamim** [comment]
@ProjectDent can I close this issue?

**Comment by ProjectDent** [comment]
Yep.
