### ISSUE TITLE
Registering asset not calling completion block

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#172]
First, calling `KPLocalAssetsManager.registerAsset` to register a widevine asset causes a crash without my recent pull request:

https://github.com/kaltura/player-sdk-native-ios/pull/170

After that fix, it's now getting further but isn't calling the completion block at all. Here's the log I get in console:

```
2016-05-16 11:44:00.605 Screeners[1997:724825] 
::Error:: -[CachedURLParams storeCacheResponse] (line:299)
(null)
2016-05-16 11:44:00.635 Screeners[1997:724816] count=2
2016-05-16 11:44:00.636 Screeners[1997:724816] count=1
2016-05-16 11:44:00.644 Screeners[1997:724825] 
::Error:: -[CachedURLParams storeCacheResponse] (line:299)
(null)
SessionSetupCompleted
~Transformer
SessionStopped
~Transformer done
```

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @ProjectDent ,

Please use the following doc:
https://vpaas.kaltura.com/documentation/05_Mobile-Video-Player-SDKs/Offline.html

It explains how to use offline, and don't forget enabling:
 // Setting this property will cache the html pages in the limit size
 config.cacheSize = 100; //MB

Let me know if it helped.

Best,

Eliza

**Comment by ProjectDent** [comment]
I've checked over our implementation of KPPlayerConfig, and the other pages of your documentation which specify how it should be set. I'm confident we are setting it up correctly:

```
        let playerConfig = KPPlayerConfig(server: "https://cdnapisec.kaltura.com", uiConfID: credentials.uiConfID, partnerId: credentials.partnerID)
        playerConfig.cacheSize = 100
        playerConfig.entryId = entitlement.vendorEntryId
        playerConfig.ks = kalturaSessionID
```

Please bear in mind the issue here is not that we're getting an error, but that we're not getting any callback at all.

**Comment by noamtamim** [comment]
@ProjectDent, I'm investigating this behavior. Any additional details you can provide will help -- like the full parameters for KPPlayerConfig and KPLocalAssetsManager. Feel free to send those via private email, of course.

Looking at your PR #170 (which I re-created as #173), I see there are some other places in KPLocalAssetsManager that don't handle all error cases. I will add some handling code and logs.

**Comment by ProjectDent** [comment]
Provided by email.

**Comment by noamtamim** [comment]
This is hopefully fixed in develop now.

**Comment by noamtamim** [comment]
@ProjectDent can I close this issue?

**Comment by ProjectDent** [comment]
I've updated to develop, and I've added the `localContentID` property. The completion block is still not being called on register asset. In the console this is what I'm getting:

```
SessionSetupCompleted
~Transformer
SessionStopped
~Transformer done
2016-05-19 15:25:27.954 Screeners[4122:1675709] 
::Error:: -[CachedURLParams storeCacheResponse] (line:299)
(null)
2016-05-19 15:25:27.986 Screeners[4122:1675849] count=2
2016-05-19 15:25:27.987 Screeners[4122:1675849] count=1
2016-05-19 15:25:27.990 Screeners[4122:1675709] 
::Error:: -[CachedURLParams storeCacheResponse] (line:299)
```

**Comment by noamtamim** [comment]
I'll continue investigating. Thanks for the feedback!

**Comment by orenk86** [comment]
Hello,

Just wondering if this issue has been resolved, as I need to integrate offline playback in one of our projects. Using Kaltura's native functionality would probably make my life easier...

Thanks!

**Comment by ProjectDent** [comment]
It has not yet been resolved.

**Comment by jessp01** [comment]
@noamtamim - any updates on this one? Thanks,

**Comment by ElizaSapir** [comment]
@ProjectDent  and @orenk86  this supposed to be resolved on our latest version.

Thanks!
