### ISSUE TITLE
Full screen bug

### ISSUE THREAD

**Issue by ElviraBurchik** [kaltura/player-sdk-native-ios#179]
### Hi, guys! 

Just implemented Kaltura player and have some strange issue: when i press on full screen button, screen becomes black and there is no any opportunity to close it or come back to previous state or screen.

**Attach screenshots:** 
Video played as usual - ![simulator screen shot may 25 2016 11 16 45 am](https://cloud.githubusercontent.com/assets/6910688/15533309/ceaf9f66-226c-11e6-82cd-988aa5cda97c.png)
Black screen after full screen button press - ![simulator screen shot may 25 2016 11 16 56 am](https://cloud.githubusercontent.com/assets/6910688/15533311/cedb0868-226c-11e6-8d33-df21df99da5a.png)

**Attach log:** 
`2016-05-25 11:28:03.985 FCB[45121:7466336] HTTP:: https://cdnapisec.kaltura.com/p/243342/sp/24334200/embedIframeJs/uiconf_id/12905712/partner_id/243342?iframeembed=true&entry_id=1_sf5ovm7u
2016-05-25 11:28:04.413 FCB[45121:7466336] HTTP:: https://cdnapisec.kaltura.com/html5/html5lib/v2.40/mwEmbedFrame.php/p/243342/uiconf_id/12905712/entry_id/1_sf5ovm7u?wid=_243342&iframeembed=true&entry_id=1_sf5ovm7u
2016-05-25 11:28:07.020 FCB[45121:7466336] _currentPlayBackTime::0.000000
`

**Attach code:** 
`import KalturaPlayerSDK

class VideoPlayerViewController: UIViewController {

    // MARK: - Properties

    private var player: KPViewController

    // MARK: - Initialization

    init(url: NSURL?) {
        player = KPViewController(URL: url)
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // MARK: - Life Cycle

    override func viewDidLoad() {
        super.viewDidLoad()

        // TODOs: Temp button to close player
        let button = UIButton(type: UIButtonType.System)
        button.frame = CGRectMake(0, 0, 50, 50)
        button.setImage(UIImage(named: "right_back_arrow"), forState: .Normal)
        button.addTarget(
            self,
            action: #selector(VideoPlayerViewController.dismissVideoPlayer),
            forControlEvents: UIControlEvents.TouchUpInside
        )

        player.loadPlayerIntoViewController(self)
        player.view.addSubview(button)
        self.view.addSubview(player.view)
    }

    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)

        NSNotificationCenter.defaultCenter().addObserver(
            self,
            selector: #selector(VideoPlayerViewController.didEnterBackground),
            name: UIApplicationDidEnterBackgroundNotification,
            object: nil
        )
    }

    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)

        NSNotificationCenter.defaultCenter().removeObserver(
            self,
            name: UIApplicationDidEnterBackgroundNotification,
            object: nil
        )
    }

    // MARK: - Private methods

    @objc private func didEnterBackground() {
        self.dismissViewControllerAnimated(false, completion: nil)
    }

    @objc private func dismissVideoPlayer() {
        player.removePlayer()
        self.dismissViewControllerAnimated(true, completion: nil)
    }

}`

**Comment by kaltura-hooks** [comment]
Hi @ElviraBurchik,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @ElviraBurchik ,

Please use the following doc about fullscreen:
https://vpaas.kaltura.com/documentation/05_Mobile-Video-Player-SDKs/Fullscreen-inline-iOS.html

Best,

Eliza
