### ISSUE TITLE
Latest Google Cast SDK causing problems.

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#193]
Hi, I have a simple test app that uses Kaltura's iOS player, v2.4.1. Here is my pod file:

target 'KalturaPlayerSDKTest' do

pod 'KalturaPlayerSDK'
pod 'Google-Mobile-Ads-SDK'
pod 'google-cast-sdk'
pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '~> 3.0.beta.16'

end

When playing a video, I get the following exception:

2016-07-22 08:40:46.074 KalturaPlayerSDKTest[29585:12271162] GoogleCast framework version 3.0.0.9352
2016-07-22 08:41:16.384 KalturaPlayerSDKTest[29585:12271162] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'filterCriteria cannot be nil'
*** First throw call stack:
(0x18255edb0 0x181bc3f80 0x18255ecf8 0x10033216c 0x1000a9070 0x1000d78b8 0x1876bcc40 0x1876bc844 0x1000a8468 0x1876d53d4 0x1876d5980 0x187793f14 0x187871508 0x1877ed114 0x18795837c 0x1876f812c 0x1876f7c28 0x1876f7ab0 0x1850519a0 0x100c51a3c 0x100c574e4 0x182514d50 0x182512bb8 0x18243cc50 0x183d24088 0x187726088 0x1000a8ab4 0x181fda8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

If I set the google-cast-sdk to an earlier version, '~> 2.10.0', the app does not crash. However, when trying to use Chromecast, the app will connect, at least it appears to do so, but it won’t play the video. And Chromecast goes blank.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jabberdabber ,

If you want to use chromecast please point to relevant version, attach the following to your podfile:
pod 'google-cast-sdk' , '~> 2.10.4’

You can use following doc that describes how to use chromecast:
https://vpaas.kaltura.com/documentation/05_Mobile-Video-Player-SDKs/iOS-Casting-Chromecast.html

**Comment by jabberdabber** [comment]
Hi Eliza, thank you for responding.

I went to the page you linked to above, and I found a link to you demo project for Chromecast:

https://github.com/kaltura/player-sdk-demo-ios/tree/master/ovp/CCDemo

I downloaded this project and also the v2.4.1 version of Kaltura's iOS Player SDK. After adding the player sdk to the CCDemo project as described in the documentation and adding the Chromecast library, I received a missing file compile error.

Specifically, Xcode said that KPCacheConfig.h was missing. This was strange because I checked and it is definitely in v2.4.1. I studied the error and as an experiment, I copied KPCacheConfig.h to the following location:

/Users/Les/Library/Developer/Xcode/DerivedData/CCDemo-arzawnmkdxvmzndtlxuiebmmefon/Build/Products/Debug-iphoneos/include

After this the CCDemo compiled, but ran into a runtime error:

2016-07-23 09:52:32.678 CCDemo[30390:12548083] ::Error:: -[KPPlayerConfig videoURL] (line:176) -- Can't resolve player root URL

So I updated the player config code to look like this (partner and player IDs obfuscated):

KPPlayerConfig *config = [[KPPlayerConfig alloc] initWithServer:@"http://cdnapi.kaltura.com"
                                                                   uiConfID:@"xxxxxxxx" // 2.45 player
                                                                  partnerId:@"xxxxxxx"];

And change the entry ID to one of our videos.

At this point, the app compiled and ran. When I tapped the 'LoadPlayer' button, the player appeared and began playing the specified video.

When I tapped the Chromecast icon in the upper righthand corner and connected to Chromecast, I saw the Kaltura logo and the text "open source video" appear on my TV. The video, however, continued playing in the app and never actually played on Chromecast.

Any advice or help will be appreciated. Thank you.

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

In demo you have on the top left corner a button, after you are connected you supposed to set the `_castProvider` you created to `castProvider` property of `KPViewController`, you can find the following method in demo:

```
- (IBAction)startCasting:(UIBarButtonItem *)sender {
    sender.tag = sender.tag ? 0 : 1;
// set castProvider!
    _player.castProvider = sender.tag ? _castProvider : nil;
    sender.tintColor = sender.tag ? [UIColor blackColor] : self.defaultTint;
}
```

**Comment by jabberdabber** [comment]
Hi @ElizaSapir,

This worked, thank you. We will need to study the demo and documentation and modify our production app accordingly. Thank you for your reply.

**Comment by Jignesh1805** [comment]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

 self.castButton = GCKUICastButton(frame: CGRect(x: 0, y: 0, width: 24, height: 24))

**Comment by snaeji** [comment]
@Jignesh1805 Did you find a solution to this? I am dealing with the same problem.

**Comment by Jignesh1805** [comment]
Yes . i solved this problem.

**Comment by Jignesh1805** [comment]
@snaeji You can initialise object first then can use this.

**Comment by ninjazoete** [comment]
@Jignesh1805 can you explain? we are creating an instance of GCKUICastButton and passing it inside UIBarButtonItem and exact same crash happens <- started happening lately

**Comment by Jignesh1805** [comment]
Create GCKUICastButton instance in global then after we can use but create
a instance may be proper way .

**Comment by nexusskv** [comment]
Hi everyone, 

Has anyone had this problem?

Added GoogleCastSDK-ios-4.5.0_static, GTMSessionFetcher, Protobuf manually to my project.
Create GCKUICastButton like this
let button = GCKUICastButton(frame: CGRect(x: CGFloat(0.0), y: CGFloat(0.0), width: CGFloat(24.0), height: CGFloat(24.0)))

Always button is nil.

In console I see this
2020-10-13 13:35:23.187001+0300 GooglecastButtonTest[2454:803800] GoogleCast framework version 4.5.0.16.01
-[GCKUICastButton initializeDefaultAccessibilityLabels] - Localized string initialization failed.
-[GCKUICastButton initializeDefaultAccessibilityLabels] - Localized string initialization failed.
-[GCKUICastButton initializeDefaultAccessibilityLabels] - Localized string initialization failed.
-[GCKUICastButton initializeDefaultAccessibilityLabels] - Localized string initialization failed.

If I added this frameworks as cocoa pods all work, but I need add manually without pods.

Please help me.
