### ISSUE TITLE
Holding on the player's control area selects the div in web view

### ISSUE THREAD

**Issue by benjaminjackson** [kaltura/player-sdk-native-ios#20]
![bug](https://cloud.githubusercontent.com/assets/12834/6604908/515d6ee6-c802-11e4-9e5f-f3198e98ac47.png)

**Comment by ElizaSapir** [comment]
Hi @benjaminjackson ,

The issue was fixed will be released on v2.29 ( Kaltura player's version ).

Best,

Eliza

**Comment by mdale** [comment]
specific commit is here: https://github.com/kaltura/mwEmbed/commit/8a772544fa43bf2ba88b2fa0fc1eae01e1b27e2b
