### ISSUE TITLE
Cocoapod seems to include too many non-core files

### ISSUE THREAD

**Issue by tbrannam** [kaltura/player-sdk-native-ios#22]
It seems that a bunch of non-kaltura files from this git repo are included when consuming the player-sdk-native-ios SDK.

so far this seems to be the minimum set of files required -

s.source_files =
"PlayerSDK/KPlayer.{h,m}","PlayerSDK/KPlayerController.{h,m}","PlayerSDK/PlayerSDK/KPViewControllerProtocols.h","PlayerSDK/KPChomecast.{h,m}","PlayerSDK/KPViewController.{h,m}","PlayerSDK/PlayerSDK/DeviceParamsHandler.{h,m}","PlayerSDK/PlayerSDK/FacebookStrategy.{h,m}","PlayerSDK/KPIMAPlayerViewController.{h,m}","PlayerSDK/PlayerSDK/NSString+Utilities.{h,m}","PlayerSDK/PlayerSDK/KPBrowserViewController.{h,m}","PlayerSDK/ChromecastDeviceController.{h,m}","PlayerSDK/PlayerSDK/KPLog.{h,m}","PlayerSDK/WVSettings.{h,m}","PlayerSDK/KalturaPlayer.{h,m}","PlayerSDK/PlayerSDK/NSDictionary+Strategy.{h,m}","PlayerSDK/PlayerSDK/MessageStrategy.{h,m}","PlayerSDK/PlayerSDK/TwitterStrategy.{h,m}","PlayerSDK/PlayerSDK/KArchiver.{h,m}","PlayerSDK/PlayerSDK/NSMutableDictionary+AdSupport.{h,m}","PlayerSDK/PlayerSDK/KPShareManager.{h,m}","PlayerSDK/KPPlayerDatasourceHandler.{h,m}","PlayerSDK/PlayerSDK/KPWebKitBrowserViewController.{h,m}","PlayerSDK/PlayerSDK/KPControlsWebView.{h,m}","PlayerSDK/KPPlayerConfig.{h,m}","PlayerSDK/PlayerSDK/GoogleplusStrategy.{h,m}","PlayerSDK/PlayerSDK/KPLogManager.{h,m}","PlayerSDK/PlayerSDK/MailStrategy.{h,m}"

**Comment by tbrannam** [comment]
DRMHandler.* should be excluded from cocoapods target since it seem to not be used, and prevents a simulator build from being compiled

**Comment by ElizaSapir** [comment]
Hi @tbrannam ,

We are going to update our pod to include only core files with no third-party libs, it's under development now it's going to be released till the end of October 2015.

Thanks!
