### ISSUE TITLE
Native notification of player controls visible state

### ISSUE THREAD

**Issue by tbrannam** [kaltura/player-sdk-native-ios#25]
I would like to hide other UI controls (navigation bar) when the video controls are hidden.   Is there a notification sent to native code when the controls autohide and autoshow?)

**Comment by tbrannam** [comment]
Starting to discover that some events are sent to the eventListener - I've added a sample to the wiki ,page.   It would be good point to a document with the event names.  Or include constants with the supported event names

**Comment by tbrannam** [comment]
I think the mwEmbed code should fire showPlayerControls and hidePlayerControls regardless of why they are being presented.   Currently these events are not triggered during an initial play (when it auto hides the controls), nor when the video stops (auto shows).

**Comment by tbrannam** [comment]
it now appears that showPlayerControls and hidePlayerControls are not fired anymore - and I don't see a way to allow the hide the video tracking controls as before

**Comment by itaykinnrot** [comment]
hi @tbrannam  is this still an issue?
