### ISSUE TITLE
Airplay support

### ISSUE THREAD

**Issue by tbrannam** [kaltura/player-sdk-native-ios#28]
Is airplay support currently functioning on Master branch - as currently it seems to not call addNativeAirPlayButton when running

**Comment by mdale** [comment]
airplay should be supported @ElizaSapir can you comment?

**Comment by ElizaSapir** [comment]
Hi @tbrannam,

Thanks for your comment, of course we support airplay :),  since we made redesign to our player sdk now the airplay and chromecast are under refactor so it will be available soon.
